name: Build, Dockerize and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-docker-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: samsung-fakestore-api
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: samsung-fakestore-api

      - name: Build Docker image
        run: |
          docker build -t . thallesf/samsung-test-api:latest 

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push thallesf/samsung-test-api:latest
